In [10]:
import pandas as pd
from Twitterpreprocessor import TwitterPreprocessor
from sklearn.feature_extraction.text import CountVectorizer
data = pd.read_csv("./twitterdataset/twitter_human_bots_dataset1.csv")
data["account_type"].value_counts()

human    25013
bot      12425
Name: account_type, dtype: int64

In [2]:
# from urllib.request import urlopen
# from urllib.error import *

# def exists(url):
# # try block to read URL
#     try:
#         x=float(url)
#         if pd.isna(x) or x==0:
#             return 0
#     except Exception:
#             try:
                
#                 html = urlopen(url)

#     # except block to catch
#     # exception
#     # and identify error
#             except Exception:
#                 return -1
            
#             else:
#                 return 1
# exists('https://t.co/7nNQF782OV')

1

# delet columns that contains nan values

In [6]:

data = data.dropna(axis=1, how='all')
data = data.dropna(subset=['account_type'])
data=data.drop_duplicates(subset="screen_name",keep='first')
data.columns

Index(['Unnamed: 0', 'created_at', 'default_profile', 'default_profile_image',
       'description', 'favourites_count', 'followers_count', 'friends_count',
       'geo_enabled', 'id', 'lang', 'location', 'profile_background_image_url',
       'profile_image_url', 'screen_name', 'statuses_count', 'verified',
       'average_tweets_per_day', 'account_age_days', 'account_type',
       'profile_image_path', 'profile_background_image_path', 'split'],
      dtype='object')

# preprocessor

In [7]:

data['description'] = data['description'].apply(lambda x :TwitterPreprocessor(str(x)).fully_preprocess().text)
data['location'] = data['location'].apply(lambda x :TwitterPreprocessor(str(x)).partially_preprocess().text)
data

,Unnamed: 0,created_at,default_profile,default_profile_image,description,favourites_count,followers_count,friends_count,geo_enabled,id,...,profile_image_url,screen_name,statuses_count,verified,average_tweets_per_day,account_age_days,account_type,profile_image_path,profile_background_image_path,split
0,0,2009-07-04 22:41:51,False,False,,5007,102,168,False,53779179,...,https://pbs.twimg.com/profile_images/128969130...,paty_castroo,3974,False,0.978,4063,bot,NaN,NaN,0
1,1,2010-01-17 22:54:19,False,False,television producer emmy award winner disney e...,1038,60,128,False,105916557,...,https://pbs.twimg.com/profile_images/632916759...,CBirckner,259,False,0.067,3866,human,profile_images/4691ae58668d932bb7e7af22141aecf...,profile_images/4691ae58668d932bb7e7af22141aecf...,0
2,2,2012-03-01 06:05:32,False,False,,2257,599,449,True,509788597,...,https://pbs.twimg.com/profile_images/128853844...,amf_jay,13627,False,4.406,3093,human,NaN,NaN,0
3,3,2009-09-01 04:52:30,False,False,,6407,116,334,True,70601327,...,https://pbs.twimg.com/profile_images/977012905...,SaraCavolo,4432,False,1.107,4005,human,profile_images/d1da9220e4aa376dff03b6f12765171...,profile_images/d1da9220e4aa376dff03b6f12765171...,0
4,4,2010-01-27 17:17:23,False,False,productor televisin embajador contacto dreamco...,20866,74448,18,True,108999927,...,https://pbs.twimg.com/profile_images/668449819...,DavidHenaoModel,15870,True,4.116,3856,human,profile_images/c65bf625b066ef5f29e14cfcf1ee91f...,profile_images/c65bf625b066ef5f29e14cfcf1ee91f...,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37433,37433,2010-12-07 08:11:16,False,False,self made plus model swim traveler wife,59660,257294,196,True,223764929,...,https://pbs.twimg.com/profile_images/712018970...,AshAlexiss,58680,True,16.562,3543,human,profile_images/a2821682b21168555a2ec5e28a3ac81...,profile_images/a2821682b21168555a2ec5e28a3ac81...,2
37434,37434,2010-12-04 13:17:22,False,False,gazetecijournalist haberdarda koordinatr,0,74666,95,False,222789645,...,https://pbs.twimg.com/profile_images/127353595...,ahmemis,41240,True,11.633,3545,human,NaN,NaN,2
37435,37435,2009-10-06 23:53:30,False,False,modelo actriz venezolana venezuelan model actr...,28,255941,236,True,80438218,...,https://pbs.twimg.com/profile_images/114651544...,Yuvannamontalvo,6692,False,1.686,3969,human,NaN,NaN,2
37436,37436,2013-03-24 21:04:16,True,False,indianactorneed,621,2678042,51,False,1296642259,...,https://pbs.twimg.com/profile_images/129570440...,IAmVarunTej,2042,True,0.755,2704,human,NaN,NaN,2
37437,37437,2011-01-10 04:01:02,False,False,poeta autor escritor dois livros publicados de...,4526,471451,15967,True,236242525,...,https://pbs.twimg.com/profile_images/129213145...,tiagopoeta,11597,False,3.305,3509,human,NaN,NaN,2

# save data

In [8]:
data.to_csv('cleandatafromkag.csv', index=False)

# descover data

In [9]:
data =data.reset_index()
data
df=pd.DataFrame(data)
df.head()

,index,Unnamed: 0,created_at,default_profile,default_profile_image,description,favourites_count,followers_count,friends_count,geo_enabled,...,profile_image_url,screen_name,statuses_count,verified,average_tweets_per_day,account_age_days,account_type,profile_image_path,profile_background_image_path,split
0,0,0,2009-07-04 22:41:51,False,False,,5007,102,168,False,...,https://pbs.twimg.com/profile_images/128969130...,paty_castroo,3974,False,0.978,4063,bot,NaN,NaN,0
1,1,1,2010-01-17 22:54:19,False,False,television producer emmy award winner disney e...,1038,60,128,False,...,https://pbs.twimg.com/profile_images/632916759...,CBirckner,259,False,0.067,3866,human,profile_images/4691ae58668d932bb7e7af22141aecf...,profile_images/4691ae58668d932bb7e7af22141aecf...,0
2,2,2,2012-03-01 06:05:32,False,False,,2257,599,449,True,...,https://pbs.twimg.com/profile_images/128853844...,amf_jay,13627,False,4.406,3093,human,NaN,NaN,0
3,3,3,2009-09-01 04:52:30,False,False,,6407,116,334,True,...,https://pbs.twimg.com/profile_images/977012905...,SaraCavolo,4432,False,1.107,4005,human,profile_images/d1da9220e4aa376dff03b6f12765171...,profile_images/d1da9220e4aa376dff03b6f12765171...,0
4,4,4,2010-01-27 17:17:23,False,False,productor televisin embajador contacto dreamco...,20866,74448,18,True,...,https://pbs.twimg.com/profile_images/668449819...,DavidHenaoModel,15870,True,4.116,3856,human,profile_images/c65bf625b066ef5f29e14cfcf1ee91f...,profile_images/c65bf625b066ef5f29e14cfcf1ee91f...,0